config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: 'user_panel/confirmations',
    passwords: 'user_panel/passwords',
    registrations: 'user_panel/registrations',
    sessions: 'user_panel/sessions'
  }

  devise_scope :user do
    get 'users/thank_you', to: 'user_panel/registrations#thank_you'
  end

  namespace :user_panel, path: :users do
    resources :checklists, only: %i[index show create update destroy] do
      resources :tasks, module: :checklists, only: %i[index create update destroy]

      member do
        get :export
        post :send_email
      end
    end

    resource :dashboard, controller: :dashboard, only: :show
    resource :otp_auth, controller: :otp_auth, only: %i[show create update destroy]
  end

  get 'up' => 'rails/health#show', as: :rails_health_check
  root 'welcome#index'
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index; end
end

app/views/welcome/index.html.haml
%nav
  .container.mx-auto
    .flex.justify-between.items-baseline.py-3
      .w-48
        %h1.text-2xl.font-bold [App Name]

      %ul.navbar
        %li= link_to 'Home', '#home', class: 'navbar__link active'
        %li= link_to 'About', '#about', class: 'navbar__link'
        %li= link_to 'Features', '#features', class: 'navbar__link'
        %li= link_to 'Benefits', '#benefits', class: 'navbar__link'
        %li= link_to 'Testimonials', '#testimonials', class: 'navbar__link'
        %li= link_to 'Pricing', '#pricing', class: 'navbar__link'
        %li= link_to 'FAQ', '#faq', class: 'navbar__link'

      %ul.navbar
        - if user_signed_in?
          %li= link_to 'Go To App', user_panel_dashboard_path, class: 'btn btn--primary'
        - else
          %li= link_to 'Sign Up', new_user_registration_path, class: 'btn btn--primary'
          %li= link_to 'Sign In', new_user_session_path, class: 'btn btn'

.landing-page
  %header#home
    .landing-page__hero
      %hgroup.text-center
        %h1.landing-page__title Stay Organized, Stay Productive
        %h3.landing-page__subtitle Manage your tasks effortlessly with [App Name] - your ultimate ToDo app for personal and professional productivity.

      .landing-page__cta
        = link_to '#', class: 'btn btn--primary' do
          %span Get Started for Free
          %i.icon.icon-arrow-right.text-2xl
        = link_to '#', class: 'btn' do
          %i.icon.icon-video.text-2xl
          %span Watch Video

      .flex.justify-center.mt-48
        = link_to '#about', class: 'btn btn--icon btn--primary animate-bounce' do
          %i.icon.icon-arrow-down.text-2xl

  %section#about
    .landing-page__section
      %h2.landing-page__section-title What is [App Name]?

      .mb-16
        %p.landing-page__section-text [App Name] is a simple yet powerful ToDo app designed to help you organize your day, manage your tasks, and boost your productivity. Whether you're planning your day-to-day activities, managing work projects, or creating grocery lists, [App Name] has everything you need to stay on top of your tasks and achieve your goals.

      %dl.stats-grid
        .stats-grid-item
          %dt.stats-grid-item__value 100K +
          %dd.stats-grid-item__text users
        .stats-grid-item
          %dt.stats-grid-item__value 2M +
          %dd.stats-grid-item__text checklists
        .stats-grid-item
          %dt.stats-grid-item__value 16M +
          %dd.stats-grid-item__text tasks
        .stats-grid-item
          %dt.stats-grid-item__value ≈ 99%
          %dd.stats-grid-item__text satisfied users

  %section#features
    .landing-page__section
      .mb-16
        %h2.landing-page__section-title What Makes Us Unique?

      .features-grid
        .features-grid-item
          .features-grid-item__icon
            %i.icon.icon-app-window
          %h4.features-grid-item__title Easy-to-Use Interface
          %p.features-grid-item__body A clean, intuitive design that makes adding, editing, and completing tasks a breeze.

        .features-grid-item
          .features-grid-item__icon
            %i.icon.icon-list-tree
          %h4.features-grid-item__title Customizable Task Lists
          %p.features-grid-item__body Create custom task lists for every part of your life – from work projects to personal goals.

        .features-grid-item
          .features-grid-item__icon
            %i.icon.icon-bell-ringing
          %h4.features-grid-item__title Smart Reminders and Notifications
          %p.features-grid-item__body Never miss a deadline with smart reminders that notify you based on your preferences.

        .features-grid-item
          .features-grid-item__icon
            %i.icon.icon-refresh
          %h4.features-grid-item__title Seamless Sync Across Devices
          %p.features-grid-item__body Access your tasks anytime, anywhere with automatic sync across all your devices.

        .features-grid-item
          .features-grid-item__icon
            %i.icon.icon-table-share
          %h4.features-grid-item__title Collaborative Features
          %p.features-grid-item__body Share lists and collaborate with family, friends, or colleagues to get things done together.

        .features-grid-item
          .features-grid-item__icon
            %i.icon.icon-progress
          %h4.features-grid-item__title Progress Tracking
          %p.features-grid-item__body Visualize your progress with our built-in tracking and analytics tools.

  -# %section#benefits
    .landing-page__section
      .mb-16
        %h2.landing-page__section-title Why Choose [App Name]?

      %div
        %div
          %h4 Stay Focused and Organized
          %p Prioritize your tasks, set deadlines, and stay on track with your daily goals.

        %div
          %h4 Boost Your Productivity
          %p Achieve more in less time with efficient task management and easy-to-use tools.

        %div
          %h4 Simplify Your Life
          %p One app to manage all aspects of your life, from work to personal tasks.

        %div
          %h4 Get Started Instantly
          %p No steep learning curve or complex setups – just sign up, and start organizing.

  %section#testimonials
    .landing-page__section
      %h2.landing-page__section-title Real Feedback from Users

      .flex.flex-col.text-center
        %figure.testimonial
          .testimonial__icon
            %i.icon.icon-quote
          %blockquote.testimonial__body
            %p "[App Name] has transformed the way I manage my day. It's simple, effective, and keeps me on track like never before!"
          %figcaption.testimonial__meta
            .testimonial__author
              .testimonial__name Sarah
              .testimonial__occupation Freelancer

        %figure.testimonial
          .testimonial__icon
            %i.icon.icon-quote
          %blockquote.testimonial__body
            %p "I love the collaborative features – it's perfect for managing tasks with my team!"
          %figcaption.testimonial__meta
            .testimonial__author
              .testimonial__name David
              .testimonial__occupation Project Manager

  -# %section#gallery
    .landing-page__section
      .mb-16
        %h2.landing-page__section-title Screenshots or Demo Video
        %h3 See [App Name] in Action

    -# Include 2-3 screenshots of the app or a short demo video showing the main features and user interface.

  -# %section#pricing.bg-white
    .landing-page__section
      .mb-16
        %h2.landing-page__section-title Clear and Transparent Pricing
        %h3 Flexible Plans for Every Need

      %ul
        %li Free Plan: "Basic task management features to get you started."
        %li Pro Plan: "$5/month – Advanced features, smart reminders, collaboration tools, and more."
        %li Enterprise Plan: "Contact us for custom solutions tailored to your business."

      %div
        = link_to 'Choose Your Plan', '#'

  %section#faq
    .landing-page__section
      %h2.landing-page__section-title Address Common Questions

      .faqs-grid
        .faqs-grid-item
          %h3.faqs-grid-item__question
            %i.icon.icon-help-hexagon-filled
            Is [App Name] free to use?
          %p.faqs-grid-item__answer Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, maxime blanditiis? Culpa enim praesentium dolorem, quam unde ex neque mollitia, quae earum, qui perferendis. Ea libero atque repellendus tempore ducimus.
        .faqs-grid-item
          %h3.faqs-grid-item__question
            %i.icon.icon-help-hexagon-filled
            How does the collaboration feature work?
          %p.faqs-grid-item__answer Lorem ipsum dolor sit, amet consectetur adipisicing elit. Dolorem autem, harum inventore minima praesentium distinctio, dolorum recusandae necessitatibus quia sit iste quasi accusamus corrupti eius sapiente obcaecati cupiditate culpa eos?
        .faqs-grid-item
          %h3.faqs-grid-item__question
            %i.icon.icon-help-hexagon-filled
            Can I use [App Name] offline?
          %p.faqs-grid-item__answer Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis, consequatur velit eveniet quos doloremque a beatae nihil, cum atque ullam in error adipisci voluptas natus. Ipsam, itaque eum? Ea, cum.
        .faqs-grid-item
          %h3.faqs-grid-item__question
            %i.icon.icon-help-hexagon-filled
            Is my data secure?
          %p.faqs-grid-item__answer Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit molestias non saepe exercitationem sed, libero, asperiores minus, nobis assumenda tempora totam beatae ullam laudantium officia molestiae aliquam et necessitatibus voluptas?

  %footer
    .landing-page__section
      .flex.flex-col.items-center.space-y-8
        %h2= link_to '[App Name]', root_path, class: ' text-2xl font-semibold text-gray-900'

        .landing-page__section-text.text-center
          Have questions? Reach out to us on social media or at
          = link_to 'support@[appname].com', 'mailto:support@[appname].com', class: 'font-medium text-indigo-600 hover:underline'

        %ul.socials-list
          %li
            = link_to '#', class: 'socials-list-item' do
              %i.icon.icon-brand-facebook
          %li
            = link_to '#', class: 'socials-list-item' do
              %i.icon.icon-brand-x
          %li
            = link_to '#', class: 'socials-list-item' do
              %i.icon.icon-brand-instagram
          %li
            = link_to '#', class: 'socials-list-item' do
              %i.icon.icon-brand-youtube
          %li
            = link_to '#', class: 'socials-list-item' do
              %i.icon.icon-brand-tiktok

        %ul.flex.flex-row.justify-center.gap-4
          %li
            = link_to 'Privacy Policy', '#', class: 'text__link text-sm'
          %li
            = link_to 'Terms of Service', '#', class: 'text__link text-sm'